# .do/app.yaml
name: ai-ui

services:
  - name: web
    # If you're building from GitHub, include your repo and branch.
    # Otherwise, remove the `github:` block if you upload via tarball.
    github:
      repo: wasabikev/ai-ui
      branch: main
      deploy_on_push: true

    # App Platform will run on a Python environment
    environment_slug: python

    # Port to listen on. Gunicorn will bind to 0.0.0.0:8080 internally.
    http_port: 8080
    
    # Number of container instances and size:
    instance_count: 1
    instance_size_slug: basic-xxs

    # Routes: one for normal HTTP and one for WebSocket
    routes:
      - path: /
        preserve_path_prefix: true
      - path: /ws/chat/status
        preserve_path_prefix: true
        type: websocket

    # Environment variables (list of key-value pairs):
    envs:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: WEBSOCKET_ENABLED
        value: "true"
      - key: WEBSOCKET_PATH
        value: "/ws/chat/status"

    # Optional: health check endpoint (Quart route or an existing endpoint)
    health_check:
      http_path: /health

    # WebSocket configuration
    websocket:
      enabled: true
      timeout: 300  # seconds
      routes:
        - path: /ws/chat/status
          preserve_path_prefix: true

