# .do/app.yaml
name: ai-ui
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: wasabikev/ai-ui
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs

    routes:
      - path: /
        preserve_path_prefix: true
      - path: /ws/chat/status
        preserve_path_prefix: true
        type: websocket

    # Environment variables must be a list of key-value pairs
    envs:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: WEBSOCKET_ENABLED
        value: "true"
      - key: WEBSOCKET_PATH
        value: "/ws/chat/status"

    # Health check
    health_check:
      http_path: /health

    # WebSocket configuration
    websocket:
      enabled: true
      timeout: 300
      routes:
        - path: /ws/chat/status
          preserve_path_prefix: true
