name: ai-ui
services:
name: web
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/ai-ui  # Replace with your actual GitHub repo
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
path: /
  health_check:
    http_path: /chat/status/health
    initial_delay_seconds: 30
    period_seconds: 60
  envs:
key: PYTHONUNBUFFERED
    value: "1"
key: QUART_APP
    value: "app:app"
key: QUART_ENV
    value: "production"
  cors:
    allow_origins:
"*"
    allow_methods:
"GET""POST""PUT""DELETE""OPTIONS"
    allow_headers:
"Content-Type""Authorization"
  headers:
path: /chat/status
    values:
      Cache-Control: no-cache
      Connection: keep-alive
      X-Accel-Buffering: "no"
      Content-Type: text/event-stream