"""add temperature and prompt template to Converstations

Revision ID: 3863e78f31de
Revises: 7c397aa3ea44
Create Date: 2023-11-22 18:22:10.174859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3863e78f31de'
down_revision = '7c397aa3ea44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prompt_template', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('prompt_template')
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
