"""Update Conversation and UploadedFile models

Revision ID: 460c7b9e82a2
Revises: 5d6ba9dabaee
Create Date: 2024-10-03 15:54:19.982021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '460c7b9e82a2'
down_revision = '5d6ba9dabaee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vector_search_results', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_search_queries', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('web_search_results', sa.JSON(), nullable=True))

    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('processed_text_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('upload_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_size')
        batch_op.drop_column('upload_timestamp')
        batch_op.drop_column('processed_text_path')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('web_search_results')
        batch_op.drop_column('generated_search_queries')
        batch_op.drop_column('vector_search_results')

    # ### end Alembic commands ###
