"""Add UploadedFile model

Revision ID: 55929376ab59
Revises: 0d0fae4ce64a
Create Date: 2024-07-04 08:59:14.810621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55929376ab59'
down_revision = '0d0fae4ce64a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('system_message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['system_message_id'], ['system_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_file')
    # ### end Alembic commands ###
