"""Add enable_web_search to SystemMessage

Revision ID: 5d6ba9dabaee
Revises: 55929376ab59
Create Date: 2024-08-20 16:06:14.403110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6ba9dabaee'
down_revision = '55929376ab59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_web_search', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_message', schema=None) as batch_op:
        batch_op.drop_column('enable_web_search')

    # ### end Alembic commands ###
