"""Increase password_hash length

Revision ID: 77836ba6e455
Revises: 61a5581cec4f
Create Date: 2025-08-14 13:22:18.028599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77836ba6e455'
down_revision = '61a5581cec4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_message', 'enable_time_sense',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('system_message', 'enable_time_sense',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
