"""Added code abstracts and changes log tables

Revision ID: 7c397aa3ea44
Revises: e83271b9ec06
Create Date: 2023-10-03 17:24:16.803507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c397aa3ea44'
down_revision = 'e83271b9ec06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codeabstract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('code_abstract', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('changeslog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abstract_id', sa.Integer(), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('change_timestamp', sa.DateTime(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['codeabstract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('changeslog')
    op.drop_table('codeabstract')
    # ### end Alembic commands ###
