"""Added support for RAG sources within system messages.

Revision ID: 86b593b45d08
Revises: 3dfc07224329
Create Date: 2024-02-18 15:37:57.193399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86b593b45d08'
down_revision = '3dfc07224329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_config', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_message', schema=None) as batch_op:
        batch_op.drop_column('source_config')

    # ### end Alembic commands ###
