"""empty message

Revision ID: 90289e400119
Revises: 3863e78f31de
Create Date: 2023-12-06 13:23:22.752594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90289e400119'
down_revision = '3863e78f31de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('changeslog_abstract_id_fkey', 'changeslog', type_='foreignkey')
    op.drop_table('changeslog')
    op.drop_table('codeabstract')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changeslog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('abstract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('change_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('change_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('change_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['codeabstract.id'], name='changeslog_abstract_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='changeslog_pkey')
    )
    op.create_table('codeabstract',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code_abstract', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name='codeabstract_conversation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='codeabstract_pkey')
    )
    # ### end Alembic commands ###
