"""Update UploadedFile model for conversation attachments

Revision ID: e307c2c299b3
Revises: bf5148fbb59e
Create Date: 2025-04-04 13:24:46.050653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e307c2c299b3'
down_revision = 'bf5148fbb59e'
branch_labels = None
depends_on = None


def upgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###

        # Step 1: Add the new columns, initially allowing NULL for processing_status and token_count
        op.add_column('uploaded_file', sa.Column('conversation_id', sa.Integer(), nullable=True))
        op.add_column('uploaded_file', sa.Column('processing_status', sa.String(length=50), nullable=True)) # Changed nullable=False to nullable=True initially
        op.add_column('uploaded_file', sa.Column('token_count', sa.Integer(), nullable=True))
        op.add_column('uploaded_file', sa.Column('is_temporary', sa.Boolean(), nullable=True)) # Add as nullable first

        # Step 2: Set default values for existing rows for the new NOT NULL columns
        # Set default processing_status for existing rows
        op.execute("UPDATE uploaded_file SET processing_status = 'pending' WHERE processing_status IS NULL")
        # Set default is_temporary for existing rows (assuming existing files should be considered permanent or adjust as needed)
        op.execute("UPDATE uploaded_file SET is_temporary = False WHERE is_temporary IS NULL")

        # Step 3: Now alter the columns to be NOT NULL
        op.alter_column('uploaded_file', 'processing_status',
                    existing_type=sa.String(length=50),
                    nullable=False)
        op.alter_column('uploaded_file', 'is_temporary',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    existing_server_default=sa.text('true')) # Add server default for future inserts

        # Make system_message_id nullable (if it wasn't already)
        op.alter_column('uploaded_file', 'system_message_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)

        # Create foreign key constraints (Alembic might generate these differently, adjust if needed)
        op.create_foreign_key(op.f('fk_uploaded_file_conversation_id_conversation'), 'uploaded_file', 'conversation', ['conversation_id'], ['id'])
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_uploaded_file_conversation_id_conversation'), 'uploaded_file', type_='foreignkey')
    op.alter_column('uploaded_file', 'system_message_id',
                existing_type=sa.INTEGER(),
                nullable=False) # Revert nullability change if needed
    op.drop_column('uploaded_file', 'is_temporary')
    op.drop_column('uploaded_file', 'token_count')
    op.drop_column('uploaded_file', 'processing_status')
    op.drop_column('uploaded_file', 'conversation_id')
    # ### end Alembic commands ###
